# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: '140.82.112.3'
      sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJy3dTMgSg8ts5XrhKAu562BXS0xUyldKf6/OCpAx/KCIMg+gjyH+f91MX7bIwlJC8pN31eVif8uRbARVeJ4LvyY2NDbRS1P9VetdPyC6mk3hrTaRNYj9NaUBvhWes5tlNw6xK4GDwl1kA1XlerTOqCrBLN0Z6IWjhfmV4QWOTBqrz9TQhW0FW/RqcF1rXr4fNX1cf99YyumSJ3pFM58AjsknRrN73MFfdTDrFGHeeSSMa1v3trvS4DtwfS4pbzj10TTskyrz7hLzGYgL8y/xWzBo6JUGrDxi9pqH6NwXjwwV5H4zTgy/yIM7sWPPcpYriACCJEJO44O0obtopsb1/c0wx96TWqHwFaw6c90GjlvtC/aIPFy5x10L6MQ6I3HYQEjxY73pYWuGfFewlHBKSDeZ4A0mUii3zxceE+eAjICZl3g/GrdQYqjk8dKzCQJgzu2T09pLioebuaT51Svmkt+nx9fXGDehzySJrj6BFi5NAbBDG0Lr2TmGVeQY5yPQyN6OK0upgTm/YL9HcMfg9vbPiLtTffRvKHS/uHZejjGOEChAg8Mb6/6wWlqNg1ahnmZvVdYi4VUbCVht7wWa8OcUVNTUH/XfjZqOjxz4fgVLuz0JVaVJBgGezcMJpM6V7BzVYGqFRzKlK7toPSZu6WhLSmA26RZdKQ5cgaZOF1Q== pubreacttogh'
      sshKeySecureFile: 'b8c31efc-4656-4b72-8910-296374ceb7f4'

  - task: DownloadSecureFile@1
    name: secureFile
    inputs:
      secureFile: 'b8c31efc-4656-4b72-8910-296374ceb7f4'
      retryCount: '2'

  - script: |
      mkdir ~/.ssh && mv $secureFile.SECUREFILEPATH ~/.ssh/id_rsa
      chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub Action"
      npm install --no-audit --progress=false
      npm run cicdcoverage
      npm run deploy
    displayName: 'npm install and deploy'
